ALTER TABLE `reference_loot_template` CHANGE `mincountOrRef` `mincountOrRef` mediumint(8) NOT NULL DEFAULT '1';
ALTER TABLE `reputation_spillover_template` CHANGE `faction` `faction` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'faction entry';
ALTER TABLE `reputation_spillover_template` CHANGE `faction1` `faction1` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'faction to give spillover for';
ALTER TABLE `reputation_spillover_template` CHANGE `faction2` `faction2` smallint(5) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `reputation_spillover_template` CHANGE `faction3` `faction3` smallint(5) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `reputation_spillover_template` CHANGE `faction4` `faction4` smallint(5) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `skinning_loot_template` CHANGE `mincountOrRef` `mincountOrRef` mediumint(8) NOT NULL DEFAULT '1';
ALTER TABLE `spell_area` CHANGE `quest_start_active` `quest_start_active` tinyint(3) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `spell_area` CHANGE `gender` `gender` tinyint(3) unsigned NOT NULL DEFAULT '2';
ALTER TABLE `spell_area` CHANGE `autocast` `autocast` tinyint(3) unsigned NOT NULL DEFAULT '0';
-- All the fields in spell_dbc where changed to full int32 since the DBC structure is used
ALTER TABLE `spell_dbc` CHANGE `Id` `Id` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `Attributes` `Attributes` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `AttributesEx` `AttributesEx` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `AttributesEx2` `AttributesEx2` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `AttributesEx3` `AttributesEx3` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `AttributesEx4` `AttributesEx4` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `AttributesEx5` `AttributesEx5` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `AttributesEx6` `AttributesEx6` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `AttributesEx7` `AttributesEx7` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `AttributesEx8` `AttributesEx8` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `CastingTimeIndex` `CastingTimeIndex` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `DurationIndex` `DurationIndex` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `PowerType` `PowerType` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `RangeIndex` `RangeIndex` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `Speed` `Speed` FLOAT NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellVisualId_1` `SpellVisualId_1` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellVisualId_2` `SpellVisualId_2` INT(10) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellIconId` `SpellIconId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `ActiveIconId` `ActiveIconId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SchoolMask` `SchoolMask` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `RuneCostId` `RuneCostId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellDifficultyId` `SpellDifficultyId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellScalingId` `SpellScalingId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellAuraOptionsId` `SpellAuraOptionsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellAuraRestrictionsId` `SpellAuraRestrictionsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellCastingRequirementsId` `SpellCastingRequirementsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellCategoriesId` `SpellCategoriesId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellClassOptionsId` `SpellClassOptionsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellCooldownsId` `SpellCooldownsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellEquippedItemsId` `SpellEquippedItemsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellInterruptsId` `SpellInterruptsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellLevelsId` `SpellLevelsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellPowerId` `SpellPowerId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellReagentsId` `SpellReagentsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellShapeshiftId` `SpellShapeshiftId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellTargetRestrictionsId` `SpellTargetRestrictionsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `SpellTotemsId` `SpellTotemsId` INT(10) NOT NULL DEFAULT '0';
ALTER TABLE `spell_dbc` CHANGE `unk` `unk` INT(10) NOT NULL DEFAULT '0';
--
ALTER TABLE `spell_group` CHANGE `id` `id` int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `spell_loot_template` CHANGE `mincountOrRef` `mincountOrRef` mediumint(8) NOT NULL DEFAULT '1';
ALTER TABLE `spell_proc` CHANGE `spellPhaseMask` `spellPhaseMask` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `spell_proc` CHANGE `hitMask` `hitMask` int(11) NOT NULL DEFAULT '0';
ALTER TABLE `spell_enchant_proc_data` CHANGE `procEx` `procEx` int(10) unsigned NOT NULL DEFAULT '0'; -- changed from float to int
ALTER TABLE `spell_required` CHANGE `spell_id` `spell_id` mediumint(8) NOT NULL DEFAULT '0';
ALTER TABLE `spell_required` CHANGE `req_spell` `req_spell` mediumint(8) NOT NULL DEFAULT '0';
ALTER TABLE `spell_threat` CHANGE `flatMod` `flatMod` int(11) NULL DEFAULT NULL;
ALTER TABLE `vehicle_accessory` CHANGE `seat_id` `seat_id` tinyint(4) NOT NULL DEFAULT '0';
ALTER TABLE `vehicle_accessory` CHANGE `minion` `minion` tinyint(3) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `vehicle_template_accessory` CHANGE `seat_id` `seat_id` tinyint(4) NOT NULL DEFAULT '0';
ALTER TABLE `vehicle_template_accessory` CHANGE `minion` `minion` tinyint(3) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `version` CHANGE `cache_id` `cache_id` int(11) NULL DEFAULT '0';
ALTER TABLE `waypoint_data` CHANGE `move_flag` `move_flag` tinyint(4) NOT NULL DEFAULT '0';
